---
- name: Download docker-compose
  ansible.builtin.get_url:
    url: "{{ docker_compose_download_url }}"
    dest: "{{ docker_compose_bin_path }}"
    checksum: "{{ docker_compose_checksum }}"
    owner: root
    group: root
    mode: 0755
  become: yes